services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: crud_analise_desenv_software_quarkus
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3305:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
